version: '3.8'

services:
  traveltrail-api:
    image: emiperezdev/traveltrail-api:latest
    container_name: traveltrail-api
    environment: 
      PORT: ${PORT}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB: ${MONGO_DB}
      MAILER_SERVICE: ${MAILER_SERVICE}
      MAILER_ACCESS_TOKEN: ${MAILER_ACCESS_TOKEN}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_EMAIL_DESTINATION: ${MAILER_EMAIL_DESTINATION}
      MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo: 
    image: mongo
    container_name: mongo-traveltrail
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27018:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
